# Generated by Django 5.0.6 on 2024-07-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('categoryName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('productName', models.CharField(max_length=15)),
                ('productDetail', models.TextField()),
                ('productDesc', models.TextField()),
                ('productInfo', models.TextField()),
                ('productMaterial', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
