# Generated by Django 5.0.6 on 2024-07-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountPrice',
            field=models.FloatField(default=170.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='productPrice',
            field=models.FloatField(default=70.0),
            preserve_default=False,
        ),
    ]
