# Generated by Django 5.0.6 on 2024-07-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_discountprice_product_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeName', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productSize',
            field=models.ManyToManyField(related_name='products', to='app.size'),
        ),
    ]
