# Generated by Django 5.0.6 on 2024-07-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_size_product_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorName', models.CharField(max_length=25)),
                ('hexValue', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='productSize',
            field=models.ManyToManyField(related_name='productSize', to='app.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='productColor',
            field=models.ManyToManyField(related_name='productColor', to='app.color'),
        ),
    ]
