# Generated by Django 5.0.6 on 2024-07-15 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_color_alter_product_productsize_product_productcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(upload_to='shopDetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('productColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.color')),
            ],
        ),
    ]
