# Generated by Django 5.0.6 on 2024-07-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productColor',
        ),
        migrations.RemoveField(
            model_name='image',
            name='productColor',
        ),
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productSize',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='size',
        ),
    ]
