# Generated by Django 5.0.6 on 2024-07-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
