# Generated by Django 5.0.6 on 2024-07-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImg',
            field=models.ImageField(default=None, upload_to='shopDtails'),
        ),
    ]
