# Generated by Django 5.0.6 on 2024-07-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_productimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productImg',
        ),
    ]
