# Generated by Django 5.0.6 on 2024-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_product_productimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImg',
            field=models.ImageField(default=123, upload_to='shopDtails'),
            preserve_default=False,
        ),
    ]
