# Generated by Django 5.0.1 on 2024-07-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_product_category_product_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productCategory',
            field=models.ManyToManyField(related_name='productCategory', to='app.category'),
        ),
    ]
