# Generated by Django 5.0.1 on 2024-07-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_product_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='id',
        ),
        migrations.AddField(
            model_name='size',
            name='sizeId',
            field=models.IntegerField(default=1000, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
