# Generated by Django 5.0.1 on 2024-07-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_size_id_size_sizeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='sizeId',
        ),
        migrations.AddField(
            model_name='size',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
