# Generated by Django 5.0.1 on 2024-07-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_size_sizeid_size_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='id',
        ),
        migrations.AddField(
            model_name='size',
            name='sizeId',
            field=models.IntegerField(default=None, primary_key=True, serialize=False, unique=True),
        ),
    ]
