# Generated by Django 5.0.1 on 2024-07-22 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_size_id_size_sizeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sizeId',
            field=models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
