# Generated by Django 5.0.1 on 2024-07-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_size_sizeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productSize',
        ),
        migrations.DeleteModel(
            name='size',
        ),
    ]
