# Generated by Django 5.0.1 on 2024-07-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_product_productsize_delete_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeName', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productSize',
            field=models.ManyToManyField(related_name='productSize', to='app.size'),
        ),
    ]
