# Generated by Django 5.0.1 on 2024-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_size_product_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sizeName',
            field=models.CharField(max_length=30),
        ),
    ]
