# Generated by Django 5.0.1 on 2024-07-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_size_sizename'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='sizeId',
            field=models.IntegerField(default=2, max_length=25),
            preserve_default=False,
        ),
    ]
