# Generated by Django 5.0.1 on 2024-07-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_size_sizeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='id',
        ),
        migrations.AlterField(
            model_name='size',
            name='sizeId',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
