# Generated by Django 5.0.1 on 2024-07-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_size_id_alter_size_sizeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productCategory',
        ),
        migrations.RemoveField(
            model_name='image',
            name='productColor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productColor',
        ),
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productSize',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='size',
        ),
    ]
