# Generated by Django 5.0.1 on 2024-07-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetail',
            name='email',
            field=models.EmailField(max_length=25, unique=True),
        ),
    ]
