# Generated by Django 5.0.6 on 2024-07-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_delete_signupdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='signUpDetail',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
