# Generated by Django 5.0.6 on 2024-07-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetail',
            name='userId',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
