# Generated by Django 5.0.1 on 2024-07-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_signupdetail_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetail',
            name='userId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
