# Generated by Django 5.0.1 on 2024-07-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_signupdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetail',
            name='email',
            field=models.EmailField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='signupdetail',
            name='userId',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
