# Generated by Django 5.0.6 on 2024-07-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_signupdetail_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdetail',
            old_name='mobile_number',
            new_name='mobileNumber',
        ),
    ]
